"""run quota job audit

Revision ID: 2c485916b4d2
Revises: f91f72539039
Create Date: 2026-10-05 19:32:16.425983

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "2c485916b4d2"
down_revision: str | None = "f91f72539039"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 本批需要挂 updated_at 触发器的表（只追加表不在其中）。
_TIMESTAMPED_TABLES: tuple[str, ...] = (
    "conversations",
    "runs",
    "messages",
    "actions",
    "quota_buckets",
    "quota_reservations",
    "jobs",
    "provider_calls",
)


def upgrade() -> None:
    # 幂等：函数可能已由前批迁移创建。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quota_buckets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "policy_version >= 0", name=op.f("ck_quota_buckets_policy_version_non_negative")
        ),
        sa.CheckConstraint("reserved >= 0", name=op.f("ck_quota_buckets_reserved_non_negative")),
        sa.CheckConstraint("used >= 0", name=op.f("ck_quota_buckets_used_non_negative")),
        sa.CheckConstraint(
            "window_end > window_start", name=op.f("ck_quota_buckets_window_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quota_buckets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_buckets")),
        sa.UniqueConstraint("id", "user_id", name="uq_quota_buckets_id_user_id"),
        sa.UniqueConstraint("user_id", "window_start", name="uq_quota_buckets_user_window"),
    )
    op.create_index(
        "ix_quota_buckets_window_start", "quota_buckets", ["window_start"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("public", "owner", name="conversationmode", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("next_message_seq", sa.BigInteger(), nullable=False),
        sa.Column("retention_policy_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("mode IN ('public', 'owner')", name=op.f("ck_conversations_mode_valid")),
        sa.CheckConstraint(
            "next_message_seq >= 1", name=op.f("ck_conversations_next_message_seq_positive")
        ),
        sa.ForeignKeyConstraint(
            ["retention_policy_id"],
            ["retention_policies.id"],
            name=op.f("fk_conversations_retention_policy_id_retention_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("id", "user_id", name="uq_conversations_id_user_id"),
    )
    op.create_index(
        "ix_conversations_active_user_id",
        "conversations",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_conversations_user_id_updated_at",
        "conversations",
        ["user_id", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("input_message_id", sa.Uuid(), nullable=True),
        sa.Column("current_message_id", sa.Uuid(), nullable=True),
        sa.Column("auth_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "waiting_input",
                "waiting_approval",
                "waiting_auth",
                "succeeded",
                "failed",
                "cancelling",
                "cancelled",
                name="runstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("scope_epoch", sa.BigInteger(), nullable=False),
        sa.Column("checkpoint_thread_id", sa.Text(), nullable=False),
        sa.Column("next_event_seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("input_request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled')) = (finished_at IS NOT NULL)",
            name=op.f("ck_runs_finished_at_matches_terminal_status"),
        ),
        sa.CheckConstraint(
            "config_snapshot IS NULL OR jsonb_typeof(config_snapshot) = 'object'",
            name=op.f("ck_runs_config_snapshot_is_object"),
        ),
        sa.CheckConstraint(
            "input_request IS NULL OR jsonb_typeof(input_request) = 'object'",
            name=op.f("ck_runs_input_request_is_object"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_input', 'waiting_approval', 'waiting_auth', 'succeeded', 'failed', 'cancelling', 'cancelled')",
            name=op.f("ck_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "length(checkpoint_thread_id) > 0", name=op.f("ck_runs_checkpoint_thread_id_not_empty")
        ),
        sa.CheckConstraint("length(request_hash) > 0", name=op.f("ck_runs_request_hash_not_empty")),
        sa.CheckConstraint("next_event_seq >= 1", name=op.f("ck_runs_next_event_seq_positive")),
        sa.CheckConstraint("scope_epoch >= 0", name=op.f("ck_runs_scope_epoch_non_negative")),
        sa.ForeignKeyConstraint(
            ["auth_session_id", "user_id"],
            ["auth_sessions.id", "auth_sessions.user_id"],
            name="fk_runs_auth_session_id_user_id",
            # NO ACTION：user_id 是 NOT NULL，SET NULL 无法完成。
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["current_message_id", "conversation_id"],
            ["messages.id", "messages.conversation_id"],
            name="fk_runs_current_message_id_messages",
            ondelete="SET NULL",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["input_message_id", "conversation_id"],
            ["messages.id", "messages.conversation_id"],
            name="fk_runs_input_message_id_messages",
            ondelete="SET NULL",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "user_id"],
            ["conversations.id", "conversations.user_id"],
            name="fk_runs_conversation_id_user_id_conversations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("id", "conversation_id", name="uq_runs_id_conversation_id"),
        sa.UniqueConstraint("id", "user_id", name="uq_runs_id_user_id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_runs_user_id_idempotency_key"),
    )
    op.create_index(
        "ix_runs_conversation_id_created_at",
        "runs",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_runs_status_created_at", "runs", ["status", "created_at"], unique=False)
    op.create_index("ix_runs_user_id_status", "runs", ["user_id", "status"], unique=False)
    op.create_index(
        "uq_runs_conversation_id_non_terminal",
        "runs",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('queued', 'running', 'waiting_input', 'waiting_approval', 'waiting_auth', 'cancelling')"
        ),
    )
    op.create_table(
        "jobs",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "waiting_auth",
                "succeeded",
                "failed",
                "cancelling",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "phase",
            sa.Enum(
                "fetching",
                "parsing",
                "embedding",
                "indexing",
                "finalizing",
                "deleting",
                name="jobphase",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("auth_session_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status = 'running') = (lease_token IS NOT NULL) AND (status = 'running') = (lease_expires_at IS NOT NULL)",
            name=op.f("ck_jobs_lease_fields_match_status"),
        ),
        sa.CheckConstraint(
            "kind ~ '^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$'", name=op.f("ck_jobs_kind_shape")
        ),
        sa.CheckConstraint(
            "payload IS NULL OR jsonb_typeof(payload) = 'object'",
            name=op.f("ck_jobs_payload_is_object"),
        ),
        sa.CheckConstraint(
            "phase IN ('fetching', 'parsing', 'embedding', 'indexing', 'finalizing', 'deleting')",
            name=op.f("ck_jobs_phase_valid"),
        ),
        sa.CheckConstraint(
            "result IS NULL OR jsonb_typeof(result) = 'object'",
            name=op.f("ck_jobs_result_is_object"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_auth', 'succeeded', 'failed', 'cancelling', 'cancelled')",
            name=op.f("ck_jobs_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint(
            "length(idempotency_key) > 0", name=op.f("ck_jobs_idempotency_key_not_empty")
        ),
        sa.CheckConstraint("length(kind) > 0", name=op.f("ck_jobs_kind_not_empty")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.CheckConstraint(
            "progress IS NULL OR (progress >= 0 AND progress <= 100)",
            name=op.f("ck_jobs_progress_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_jobs_actor_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_jobs_auth_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_jobs_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_jobs_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
    )
    op.create_index("ix_jobs_lease_expires_at", "jobs", ["lease_expires_at"], unique=False)
    op.create_index("ix_jobs_resource_id", "jobs", ["resource_id"], unique=False)
    op.create_index("ix_jobs_run_id", "jobs", ["run_id"], unique=False)
    op.create_index("ix_jobs_status_available_at", "jobs", ["status", "available_at"], unique=False)
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="messagerole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("content_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "composing",
                "complete",
                "interrupted",
                "hidden",
                name="messagestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("client_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f("ck_messages_role_valid")),
        sa.CheckConstraint(
            "status IN ('composing', 'complete', 'interrupted', 'hidden')",
            name=op.f("ck_messages_status_valid"),
        ),
        sa.CheckConstraint(
            "content_version >= 1", name=op.f("ck_messages_content_version_positive")
        ),
        sa.CheckConstraint("seq >= 1", name=op.f("ck_messages_seq_positive")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "conversation_id"],
            ["runs.id", "runs.conversation_id"],
            name="fk_messages_run_id_conversation_id",
            # NO ACTION：conversation_id 是 NOT NULL，SET NULL 无法完成。
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "seq", name="uq_messages_conversation_seq"),
        sa.UniqueConstraint("id", "conversation_id", name="uq_messages_id_conversation_id"),
    )
    op.create_index(
        "ix_messages_conversation_id_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    op.create_index(
        "uq_messages_conversation_id_client_message_id",
        "messages",
        ["conversation_id", "client_message_id"],
        unique=True,
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.create_table(
        "quota_reservations",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "reserved",
                "charged",
                "released",
                "refunded",
                name="quotareservationstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("charged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "status <> 'reserved' OR charged_at IS NULL",
            name=op.f("ck_quota_reservations_reserved_not_charged"),
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'charged', 'released', 'refunded')",
            name=op.f("ck_quota_reservations_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('released', 'refunded') OR settled_at IS NOT NULL",
            name=op.f("ck_quota_reservations_settled_at_matches_terminal_status"),
        ),
        sa.CheckConstraint("amount = 1", name=op.f("ck_quota_reservations_amount_is_one")),
        sa.ForeignKeyConstraint(
            ["bucket_id", "user_id"],
            ["quota_buckets.id", "quota_buckets.user_id"],
            name="fk_quota_reservations_bucket_id_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "user_id"],
            ["runs.id", "runs.user_id"],
            name="fk_quota_reservations_run_id_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_reservations")),
        sa.UniqueConstraint("run_id", name="uq_quota_reservations_run_id"),
    )
    op.create_index(
        "ix_quota_reservations_bucket_id_status",
        "quota_reservations",
        ["bucket_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_quota_reservations_user_id_created_at",
        "quota_reservations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "run.status",
                "message.snapshot",
                "tool.started",
                "tool.finished",
                "knowledge.processing",
                "action.proposed",
                "action.succeeded",
                "source.invalidated",
                "scope.changed",
                "error",
                "done",
                name="runeventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payload IS NULL OR jsonb_typeof(payload) = 'object'",
            name=op.f("ck_run_events_payload_is_object"),
        ),
        sa.CheckConstraint(
            "type IN ('run.status', 'message.snapshot', 'tool.started', 'tool.finished', 'knowledge.processing', 'action.proposed', 'action.succeeded', 'source.invalidated', 'scope.changed', 'error', 'done')",
            name=op.f("ck_run_events_type_valid"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_run_events_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", "seq", name=op.f("pk_run_events")),
    )
    op.create_index(
        "ix_run_events_run_id_created_at", "run_events", ["run_id", "created_at"], unique=False
    )
    op.create_table(
        "actions",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("auth_session_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("authorization_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "publish",
                "revoke",
                "delete",
                "update_settings",
                "provide_input",
                "create_memory",
                "update_memory",
                "delete_memory",
                "apply_retention",
                name="actiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_resource_id", sa.Uuid(), nullable=True),
        sa.Column("expected_version", sa.BigInteger(), nullable=True),
        sa.Column("expected_acl_version", sa.BigInteger(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters_hash", sa.Text(), nullable=False),
        sa.Column(
            "authorization_kind",
            sa.Enum(
                "explicit_request",
                "confirmed_preview",
                name="actionauthorizationkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "awaiting_confirmation",
                "ready",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                "expired",
                name="actionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status = 'succeeded') = (executed_at IS NOT NULL)",
            name=op.f("ck_actions_executed_at_matches_status"),
        ),
        sa.CheckConstraint(
            "authorization_kind IN ('explicit_request', 'confirmed_preview')",
            name=op.f("ck_actions_authorization_kind_valid"),
        ),
        sa.CheckConstraint(
            "parameters IS NULL OR jsonb_typeof(parameters) = 'object'",
            name=op.f("ck_actions_parameters_is_object"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'awaiting_confirmation', 'ready', 'running', 'succeeded', 'failed', 'cancelled', 'expired')",
            name=op.f("ck_actions_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('proposed', 'awaiting_confirmation') OR confirmed_at IS NULL",
            name=op.f("ck_actions_unconfirmed_has_no_confirmed_at"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('ready', 'running', 'succeeded', 'failed') OR confirmed_at IS NOT NULL",
            name=op.f("ck_actions_confirmed_statuses_require_confirmed_at"),
        ),
        sa.CheckConstraint(
            "type IN ('publish', 'revoke', 'delete', 'update_settings', 'provide_input', 'create_memory', 'update_memory', 'delete_memory', 'apply_retention')",
            name=op.f("ck_actions_type_valid"),
        ),
        sa.CheckConstraint(
            "expected_acl_version IS NULL OR expected_acl_version >= 0",
            name=op.f("ck_actions_expected_acl_version_non_negative"),
        ),
        sa.CheckConstraint(
            "expected_version IS NULL OR expected_version >= 0",
            name=op.f("ck_actions_expected_version_non_negative"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_actions_expires_after_created")
        ),
        sa.CheckConstraint(
            "length(parameters_hash) > 0", name=op.f("ck_actions_parameters_hash_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_actions_actor_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_actions_auth_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["authorization_message_id"],
            ["messages.id"],
            name=op.f("fk_actions_authorization_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_actions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_resource_id"],
            ["resources.id"],
            name=op.f("fk_actions_target_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint(
            "actor_id", "idempotency_key", name="uq_actions_actor_id_idempotency_key"
        ),
    )
    op.create_index("ix_actions_run_id_status", "actions", ["run_id", "status"], unique=False)
    op.create_index(
        "ix_actions_status_expires_at", "actions", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "ix_actions_target_resource_id", "actions", ["target_resource_id"], unique=False
    )
    op.create_table(
        "provider_calls",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "chat",
                "tool",
                "embedding",
                "rerank",
                "search",
                "fetch",
                "email",
                name="providercallpurpose",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("logical_call_key", sa.Text(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "prepared",
                "dispatched",
                "succeeded",
                "failed",
                "unknown",
                name="providercallstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("external_request_id", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("search_units", sa.BigInteger(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('chat', 'tool', 'embedding', 'rerank', 'search', 'fetch', 'email')",
            name=op.f("ck_provider_calls_purpose_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'prepared' OR started_at IS NULL",
            name=op.f("ck_provider_calls_prepared_not_started"),
        ),
        sa.CheckConstraint(
            "status IN ('prepared', 'dispatched', 'succeeded', 'failed', 'unknown')",
            name=op.f("ck_provider_calls_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('succeeded', 'failed', 'unknown') OR finished_at IS NOT NULL",
            name=op.f("ck_provider_calls_finished_at_matches_terminal_status"),
        ),
        sa.CheckConstraint(
            "(estimated_cost IS NULL AND actual_cost IS NULL) OR currency IS NOT NULL",
            name=op.f("ck_provider_calls_currency_required_with_cost"),
        ),
        sa.CheckConstraint(
            "actual_cost IS NULL OR actual_cost >= 0",
            name=op.f("ck_provider_calls_actual_cost_non_negative"),
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_provider_calls_attempt_no_positive")),
        sa.CheckConstraint(
            "currency IS NULL OR length(currency) = 3",
            name=op.f("ck_provider_calls_currency_shape"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_provider_calls_estimated_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_provider_calls_input_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "length(logical_call_key) > 0",
            name=op.f("ck_provider_calls_logical_call_key_not_empty"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_provider_calls_output_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "run_id IS NOT NULL OR job_id IS NOT NULL",
            name=op.f("ck_provider_calls_traceable_target"),
        ),
        sa.CheckConstraint(
            "search_units IS NULL OR search_units >= 0",
            name=op.f("ck_provider_calls_search_units_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_provider_calls_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_provider_calls_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_calls")),
        sa.UniqueConstraint(
            "logical_call_key", "attempt_no", name="uq_provider_calls_logical_key_attempt"
        ),
    )
    op.create_index("ix_provider_calls_job_id", "provider_calls", ["job_id"], unique=False)
    op.create_index(
        "ix_provider_calls_provider_created_at",
        "provider_calls",
        ["provider", "created_at"],
        unique=False,
    )
    op.create_index("ix_provider_calls_run_id", "provider_calls", ["run_id"], unique=False)
    op.create_index(
        "ix_provider_calls_status_created_at",
        "provider_calls",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "succeeded", "failed", "denied", name="auditresult", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("before_version", sa.BigInteger(), nullable=True),
        sa.Column("after_version", sa.BigInteger(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type ~ '^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$'",
            name=op.f("ck_audit_events_event_type_shape"),
        ),
        sa.CheckConstraint(
            "metadata_json IS NULL OR jsonb_typeof(metadata_json) = 'object'",
            name=op.f("ck_audit_events_metadata_is_object"),
        ),
        sa.CheckConstraint(
            "result IN ('succeeded', 'failed', 'denied')", name=op.f("ck_audit_events_result_valid")
        ),
        sa.CheckConstraint(
            "after_version IS NULL OR after_version >= 0",
            name=op.f("ck_audit_events_after_version_non_negative"),
        ),
        sa.CheckConstraint(
            "before_version IS NULL OR before_version >= 0",
            name=op.f("ck_audit_events_before_version_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
            name=op.f("fk_audit_events_action_id_actions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_audit_events_resource_id_resources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_action_id", "audit_events", ["action_id"], unique=False)
    op.create_index(
        "ix_audit_events_actor_id_created_at",
        "audit_events",
        ["actor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_event_type_created_at",
        "audit_events",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_resource_id_created_at",
        "audit_events",
        ["resource_id", "created_at"],
        unique=False,
    )
    # 延迟外键的实际创建位置：``use_alter=True`` 的约束不会被批次二的
    # ``create_table`` 发射（内联声明只是元数据描述），autogenerate 会把它
    # 生成在**下一个** revision 里。因此 resources.current_revision_id 的
    # 归属外键在批次三才真正建立。
    #
    # NO ACTION 而不是 SET NULL：SET NULL 会把列组里每一列都置空，
    # 而 id 是 NOT NULL 主键，该动作永远无法完成。
    op.create_foreign_key(
        "fk_resources_current_revision_id_resource_versions",
        "resources",
        "resource_versions",
        ["current_revision_id", "id"],
        ["id", "resource_id"],
        ondelete="NO ACTION",
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_resources_current_revision_id_resource_versions", "resources", type_="foreignkey"
    )
    op.drop_index("ix_audit_events_resource_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_event_type_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_action_id", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_provider_calls_status_created_at", table_name="provider_calls")
    op.drop_index("ix_provider_calls_run_id", table_name="provider_calls")
    op.drop_index("ix_provider_calls_provider_created_at", table_name="provider_calls")
    op.drop_index("ix_provider_calls_job_id", table_name="provider_calls")
    op.drop_table("provider_calls")
    op.drop_index("ix_actions_target_resource_id", table_name="actions")
    op.drop_index("ix_actions_status_expires_at", table_name="actions")
    op.drop_index("ix_actions_run_id_status", table_name="actions")
    op.drop_table("actions")
    op.drop_index("ix_run_events_run_id_created_at", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_quota_reservations_user_id_created_at", table_name="quota_reservations")
    op.drop_index("ix_quota_reservations_bucket_id_status", table_name="quota_reservations")
    op.drop_table("quota_reservations")
    op.drop_index(
        "uq_messages_conversation_id_client_message_id",
        table_name="messages",
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_jobs_status_available_at", table_name="jobs")
    op.drop_index("ix_jobs_run_id", table_name="jobs")
    op.drop_index("ix_jobs_resource_id", table_name="jobs")
    op.drop_index("ix_jobs_lease_expires_at", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        "uq_runs_conversation_id_non_terminal",
        table_name="runs",
        postgresql_where=sa.text(
            "status IN ('queued', 'running', 'waiting_input', 'waiting_approval', 'waiting_auth', 'cancelling')"
        ),
    )
    op.drop_index("ix_runs_user_id_status", table_name="runs")
    op.drop_index("ix_runs_status_created_at", table_name="runs")
    op.drop_index("ix_runs_conversation_id_created_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_conversations_user_id_updated_at", table_name="conversations")
    op.drop_index(
        "ix_conversations_active_user_id",
        table_name="conversations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("conversations")
    op.drop_index("ix_quota_buckets_window_start", table_name="quota_buckets")
    op.drop_table("quota_buckets")
    # ### end Alembic commands ###
