"""content publication retrieval

Revision ID: f529e702ea13
Revises: 78495a1757ad
Create Date: 2026-10-05 17:53:07.722019

第二批表（实施顺序 A5）：resources / resource_versions / publications /
comments / knowledge_indexes / run_sources。

autogenerate 之外的手工补充：``updated_at`` 触发器。
触发器函数已在第一批迁移里创建（``CREATE OR REPLACE`` 可重复执行），
这里只需为新增的带 ``updated_at`` 表挂上触发器。
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "f529e702ea13"
down_revision: str | None = "78495a1757ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 本批迁移中需要挂 updated_at 触发器的表。
_TIMESTAMPED_TABLES = (
    "resources",
    "resource_versions",
    "publications",
    "comments",
    "knowledge_indexes",
    "run_sources",
)


def upgrade() -> None:
    # 幂等：函数可能已由第一批迁移创建（例如分批部署或重建环境）。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "article", "web_page", "file", name="resourcetype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("private_note", sa.Text(), nullable=True),
        sa.Column("acl_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "type IN ('article', 'web_page', 'file')", name=op.f("ck_resources_type_valid")
        ),
        sa.CheckConstraint("acl_version >= 0", name=op.f("ck_resources_acl_version_non_negative")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_resources_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
    )
    op.create_index(
        "ix_resources_deleted_at_archived_at",
        "resources",
        ["deleted_at", "archived_at"],
        unique=False,
    )
    op.create_index(
        "ix_resources_owner_id_type_created_at",
        "resources",
        ["owner_id", "type", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_resources_owner_id_slug",
        "resources",
        ["owner_id", "slug"],
        unique=True,
        postgresql_where=sa.text("slug IS NOT NULL"),
    )
    op.create_table(
        "comments",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("visible", "hidden", name="commentstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("moderation_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('visible', 'hidden')", name=op.f("ck_comments_status_valid")
        ),
        sa.CheckConstraint("length(body) > 0", name=op.f("ck_comments_body_not_empty")),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_comments_parent_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_comments_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint("author_id", "client_id", name="uq_comments_author_client"),
    )
    op.create_index(
        "ix_comments_author_id_created_at", "comments", ["author_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_comments_parent_id_created_at", "comments", ["parent_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_comments_resource_id_created_at",
        "comments",
        ["resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "resource_versions",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "content_format",
            sa.Enum("markdown", "html", "text", name="contentformat", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "content_format IN ('markdown', 'html', 'text')",
            name=op.f("ck_resource_versions_content_format_valid"),
        ),
        sa.CheckConstraint(
            "(storage_key IS NULL) = (mime_type IS NULL) AND (storage_key IS NULL) = (size_bytes IS NULL)",
            name=op.f("ck_resource_versions_storage_metadata_consistent"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_resource_versions_size_bytes_non_negative"),
        ),
        sa.CheckConstraint(
            "version_no >= 1", name=op.f("ck_resource_versions_version_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_resource_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_resource_versions_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_versions")),
        sa.UniqueConstraint(
            "resource_id", "version_no", name="uq_resource_versions_resource_version_no"
        ),
    )
    op.create_index(
        "ix_resource_versions_resource_id_created_at",
        "resource_versions",
        ["resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "publications",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_version_id", sa.Uuid(), nullable=False),
        sa.Column("resource_version", sa.Integer(), nullable=False),
        sa.Column("acl_version_at_publish", sa.Integer(), nullable=False),
        sa.Column("public_no", sa.Integer(), nullable=False),
        sa.Column("public_url", sa.String(length=2048), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revoked_reason",
            sa.Enum(
                "republished",
                "owner_revoked",
                "admin_takedown",
                "resource_deleted",
                name="publicationrevokereason",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revoked_reason IN ('republished', 'owner_revoked', 'admin_takedown', 'resource_deleted')",
            name=op.f("ck_publications_revoked_reason_valid"),
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_reason IS NULL)",
            name=op.f("ck_publications_revocation_marker_consistent"),
        ),
        sa.CheckConstraint(
            "acl_version_at_publish >= 0",
            name=op.f("ck_publications_acl_version_at_publish_non_negative"),
        ),
        sa.CheckConstraint("public_no >= 1", name=op.f("ck_publications_public_no_positive")),
        sa.CheckConstraint(
            "resource_version >= 1", name=op.f("ck_publications_resource_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_publications_published_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_publications_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_version_id"],
            ["resource_versions.id"],
            name=op.f("fk_publications_resource_version_id_resource_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint("public_no", name="uq_publications_public_no"),
        sa.UniqueConstraint("public_url", name="uq_publications_public_url"),
    )
    op.create_index(
        "ix_publications_resource_id_published_at",
        "publications",
        ["resource_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_publications_resource_id_current",
        "publications",
        ["resource_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "knowledge_indexes",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column(
            "corpus_kind",
            sa.Enum("private", "public", name="indexkind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "source_kind",
            sa.Enum(
                "resource_version",
                "publication",
                name="indexsourcekind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("resource_version_id", sa.Uuid(), nullable=True),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("fragment_start", sa.Integer(), nullable=False),
        sa.Column("fragment_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(corpus_kind = 'private' AND source_kind = 'resource_version' AND resource_version_id IS NOT NULL AND publication_id IS NULL) OR (corpus_kind = 'public' AND source_kind = 'publication' AND publication_id IS NOT NULL AND resource_version_id IS NULL)",
            name=op.f("ck_knowledge_indexes_corpus_source_consistent"),
        ),
        sa.CheckConstraint(
            "corpus_kind IN ('private', 'public')",
            name=op.f("ck_knowledge_indexes_corpus_kind_valid"),
        ),
        sa.CheckConstraint(
            "source_kind IN ('resource_version', 'publication')",
            name=op.f("ck_knowledge_indexes_source_kind_valid"),
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_knowledge_indexes_chunk_index_non_negative")
        ),
        sa.CheckConstraint(
            "embedding_dimensions = 1024",
            name=op.f("ck_knowledge_indexes_embedding_dimensions_matches_column"),
        ),
        sa.CheckConstraint(
            "fragment_end > fragment_start",
            name=op.f("ck_knowledge_indexes_fragment_range_ordered"),
        ),
        sa.CheckConstraint(
            "fragment_start >= 0", name=op.f("ck_knowledge_indexes_fragment_start_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_knowledge_indexes_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_knowledge_indexes_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_knowledge_indexes_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_version_id"],
            ["resource_versions.id"],
            name=op.f("fk_knowledge_indexes_resource_version_id_resource_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_indexes")),
        sa.UniqueConstraint(
            "corpus_kind",
            "resource_id",
            "chunk_id",
            name="uq_knowledge_indexes_corpus_resource_chunk",
        ),
    )
    op.create_index(
        "ix_knowledge_indexes_chunk_id", "knowledge_indexes", ["chunk_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_indexes_embedding_hnsw",
        "knowledge_indexes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_index(
        "ix_knowledge_indexes_owner_id_corpus_kind",
        "knowledge_indexes",
        ["owner_id", "corpus_kind"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_indexes_resource_id_corpus_kind",
        "knowledge_indexes",
        ["resource_id", "corpus_kind"],
        unique=False,
    )
    op.create_table(
        "run_sources",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "grounding",
            sa.Enum("private", "public", name="runsourcekind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("resource_version_id", sa.Uuid(), nullable=True),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column("acl_version", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("fragment_start", sa.Integer(), nullable=True),
        sa.Column("fragment_end", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("cited", sa.Boolean(), nullable=False),
        sa.Column("retrieval_model", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(grounding = 'private' AND publication_id IS NULL) OR (grounding = 'public' AND resource_version_id IS NULL)",
            name=op.f("ck_run_sources_grounding_target_consistent"),
        ),
        sa.CheckConstraint(
            "grounding IN ('private', 'public')", name=op.f("ck_run_sources_grounding_valid")
        ),
        sa.CheckConstraint(
            "(fragment_start IS NULL) = (fragment_end IS NULL)",
            name=op.f("ck_run_sources_fragment_markers_consistent"),
        ),
        sa.CheckConstraint(
            "acl_version >= 0", name=op.f("ck_run_sources_acl_version_non_negative")
        ),
        sa.CheckConstraint(
            "fragment_end IS NULL OR fragment_end > fragment_start",
            name=op.f("ck_run_sources_fragment_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_run_sources_publication_id_publications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_run_sources_resource_id_resources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_version_id"],
            ["resource_versions.id"],
            name=op.f("fk_run_sources_resource_version_id_resource_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_sources")),
        sa.UniqueConstraint("run_id", "chunk_id", name="uq_run_sources_run_chunk"),
    )
    op.create_index("ix_run_sources_resource_id", "run_sources", ["resource_id"], unique=False)
    op.create_index("ix_run_sources_run_id", "run_sources", ["run_id"], unique=False)
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_sources_run_id", table_name="run_sources")
    op.drop_index("ix_run_sources_resource_id", table_name="run_sources")
    op.drop_table("run_sources")
    op.drop_index("ix_knowledge_indexes_resource_id_corpus_kind", table_name="knowledge_indexes")
    op.drop_index("ix_knowledge_indexes_owner_id_corpus_kind", table_name="knowledge_indexes")
    op.drop_index(
        "ix_knowledge_indexes_embedding_hnsw",
        table_name="knowledge_indexes",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index("ix_knowledge_indexes_chunk_id", table_name="knowledge_indexes")
    op.drop_table("knowledge_indexes")
    op.drop_index(
        "uq_publications_resource_id_current",
        table_name="publications",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_publications_resource_id_published_at", table_name="publications")
    op.drop_table("publications")
    op.drop_index("ix_resource_versions_resource_id_created_at", table_name="resource_versions")
    op.drop_table("resource_versions")
    op.drop_index("ix_comments_resource_id_created_at", table_name="comments")
    op.drop_index("ix_comments_parent_id_created_at", table_name="comments")
    op.drop_index("ix_comments_author_id_created_at", table_name="comments")
    op.drop_table("comments")
    op.drop_index(
        "uq_resources_owner_id_slug",
        table_name="resources",
        postgresql_where=sa.text("slug IS NOT NULL"),
    )
    op.drop_index("ix_resources_owner_id_type_created_at", table_name="resources")
    op.drop_index("ix_resources_deleted_at_archived_at", table_name="resources")
    op.drop_table("resources")
    # ### end Alembic commands ###
