"""identity foundation

Revision ID: 78495a1757ad
Revises:
Create Date: 2026-10-05 17:35:38.420480

第一批表（实施顺序 A3）：users / auth_sessions / auth_tokens / admin_factors /
rate_limit_buckets / settings。

autogenerate 之外的手工补充：``updated_at`` 触发器。
SQLAlchemy 元数据里没有触发器概念，因此迁移必须显式创建触发器函数，
并为每张带 ``updated_at`` 的表挂上触发器（见 ``db/timestamps.py``）。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    DROP_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "78495a1757ad"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 本批迁移中需要挂 updated_at 触发器的表。
_TIMESTAMPED_TABLES = (
    "users",
    "admin_factors",
    "auth_sessions",
    "auth_tokens",
    "rate_limit_buckets",
    "settings",
)


def upgrade() -> None:
    # 触发器函数先于任何表存在（幂等，后续批次迁移可重复创建）。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_canonical", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "role",
            sa.Enum("member", "owner", name="role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("content_schema_version", sa.Integer(), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_quota_override", sa.Integer(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("role IN ('member', 'owner')", name=op.f("ck_users_role_valid")),
        sa.CheckConstraint(
            "content_schema_version >= 1", name=op.f("ck_users_content_schema_version_positive")
        ),
        sa.CheckConstraint(
            "daily_quota_override IS NULL OR daily_quota_override >= 0",
            name=op.f("ck_users_daily_quota_override_non_negative"),
        ),
        sa.CheckConstraint(
            "email_canonical = lower(btrim(email_canonical))",
            name=op.f("ck_users_email_canonical_normalized"),
        ),
        sa.CheckConstraint("session_version >= 1", name=op.f("ck_users_session_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_canonical", name="uq_users_email_canonical"),
    )
    op.create_index("ix_users_cooldown_until", "users", ["cooldown_until"], unique=False)
    op.create_index("ix_users_role_created_at", "users", ["role", "created_at"], unique=False)
    op.create_table(
        "admin_factors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "factor_type",
            sa.Enum("totp", "recovery_code", name="adminfactortype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("secret_ciphertext", sa.String(length=512), nullable=False),
        sa.Column("recovery_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "factor_type IN ('totp', 'recovery_code')",
            name=op.f("ck_admin_factors_factor_type_valid"),
        ),
        sa.CheckConstraint(
            "length(secret_ciphertext) > 0",
            name=op.f("ck_admin_factors_secret_ciphertext_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_factors_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_factors")),
    )
    op.create_index(
        "ix_admin_factors_user_type_active",
        "admin_factors",
        ["user_id", "factor_type"],
        unique=True,
        postgresql_where=sa.text("is_active AND disabled_at IS NULL"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("csrf_version", sa.Integer(), nullable=False),
        sa.Column("created_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_session_id", sa.Uuid(), nullable=True),
        sa.Column("step_up_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_totp_step", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(replaced_by_session_id IS NULL) = (rotated_at IS NULL)",
            name=op.f("ck_auth_sessions_rotation_marker_consistent"),
        ),
        sa.CheckConstraint(
            "csrf_version >= 1", name=op.f("ck_auth_sessions_csrf_version_positive")
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_sessions_expires_after_created")
        ),
        sa.CheckConstraint(
            "session_version >= 1", name=op.f("ck_auth_sessions_session_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_sessions_replaced_by_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_auth_sessions_token_hash"),
    )
    op.create_index("ix_auth_sessions_expires_at", "auth_sessions", ["expires_at"], unique=False)
    op.create_index(
        "ix_auth_sessions_user_id_revoked_at",
        "auth_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "auth_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "email_verify",
                "password_reset",
                "step_up",
                "admin_bootstrap",
                name="authtokenpurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("created_ip", sa.String(length=64), nullable=True),
        sa.Column("created_user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('email_verify', 'password_reset', 'step_up', 'admin_bootstrap')",
            name=op.f("ck_auth_tokens_purpose_valid"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_tokens_expires_after_created")
        ),
        sa.CheckConstraint(
            "failed_attempts >= 0", name=op.f("ck_auth_tokens_failed_attempts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_tokens")),
        sa.UniqueConstraint(
            "purpose", "user_id", "client_id", name="uq_auth_tokens_purpose_user_client"
        ),
        sa.UniqueConstraint("token_hash", name="uq_auth_tokens_token_hash"),
    )
    op.create_index("ix_auth_tokens_expires_at", "auth_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_auth_tokens_user_id_purpose", "auth_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "rate_limit_buckets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("count >= 0", name=op.f("ck_rate_limit_buckets_count_non_negative")),
        sa.CheckConstraint(
            "window_seconds > 0", name=op.f("ck_rate_limit_buckets_window_seconds_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_rate_limit_buckets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_buckets")),
        sa.UniqueConstraint("user_id", "window_start", name="uq_rate_limit_buckets_user_window"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "string",
                "integer",
                "boolean",
                "json",
                name="settingvaluetype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_type IN ('string', 'integer', 'boolean', 'json')",
            name=op.f("ck_settings_value_type_valid"),
        ),
        sa.CheckConstraint("key = lower(key)", name=op.f("ck_settings_key_lowercase")),
        sa.CheckConstraint("length(key) > 0", name=op.f("ck_settings_key_not_empty")),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_table("rate_limit_buckets")
    op.drop_index("ix_auth_tokens_user_id_purpose", table_name="auth_tokens")
    op.drop_index("ix_auth_tokens_expires_at", table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_index("ix_auth_sessions_user_id_revoked_at", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_expires_at", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(
        "ix_admin_factors_user_type_active",
        table_name="admin_factors",
        postgresql_where=sa.text("is_active AND disabled_at IS NULL"),
    )
    op.drop_table("admin_factors")
    op.drop_index("ix_users_role_created_at", table_name="users")
    op.drop_index("ix_users_cooldown_until", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # 触发器函数在所有表都已删除后才可安全移除。
    op.execute(DROP_UPDATED_AT_FUNCTION_SQL)
