"""run quota job audit

Revision ID: 4c4f5ba032f4
Revises: f529e702ea13
Create Date: 2026-10-05 18:03:37.533281

第三批表（实施顺序 A6）：conversations / messages / runs / run_events /
quota_buckets / quota_reservations / jobs / provider_calls / audit_events / actions。

同时给 A5 建立的 ``run_sources.run_id`` 补上指向 ``runs`` 的外键
（A5 时 runs 表尚不存在）。

autogenerate 之外的手工补充：``updated_at`` 触发器。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "4c4f5ba032f4"
down_revision: str | None = "f529e702ea13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 本批迁移中需要挂 updated_at 触发器的表。
_TIMESTAMPED_TABLES = (
    "conversations",
    "messages",
    "runs",
    "run_events",
    "quota_buckets",
    "quota_reservations",
    "jobs",
    "provider_calls",
    "audit_events",
    "actions",
)


def upgrade() -> None:
    # 幂等：函数可能已由前批迁移创建。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("public", "owner", name="conversationmode", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "model_profile",
            sa.Enum(
                "primary",
                "fast",
                "embedding",
                "rerank",
                name="modelprofile",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("content_acl_epoch_at_start", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("mode IN ('public', 'owner')", name=op.f("ck_conversations_mode_valid")),
        sa.CheckConstraint(
            "model_profile IN ('primary', 'fast', 'embedding', 'rerank')",
            name=op.f("ck_conversations_model_profile_valid"),
        ),
        sa.CheckConstraint(
            "content_acl_epoch_at_start >= 0",
            name=op.f("ck_conversations_acl_epoch_at_start_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("thread_id", name="uq_conversations_thread_id"),
    )
    op.create_index(
        "ix_conversations_user_id_created_at",
        "conversations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_user_id_last_activity_at",
        "conversations",
        ["user_id", "last_activity_at"],
        unique=False,
    )
    op.create_table(
        "quota_buckets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_timezone", sa.String(length=64), nullable=False),
        sa.Column("limit_value", sa.Integer(), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "limit_value >= 0", name=op.f("ck_quota_buckets_limit_value_non_negative")
        ),
        sa.CheckConstraint("reserved >= 0", name=op.f("ck_quota_buckets_reserved_non_negative")),
        sa.CheckConstraint(
            "used + reserved <= limit_value", name=op.f("ck_quota_buckets_usage_within_limit")
        ),
        sa.CheckConstraint("used >= 0", name=op.f("ck_quota_buckets_used_non_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quota_buckets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_buckets")),
        sa.UniqueConstraint("user_id", "window_start", name="uq_quota_buckets_user_window"),
    )
    op.create_index(
        "ix_quota_buckets_window_start", "quota_buckets", ["window_start"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("quota_bucket_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "waiting_input",
                "succeeded",
                "failed",
                "cancelled",
                name="runstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("public", "owner", name="conversationmode", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "model_profile",
            sa.Enum(
                "primary",
                "fast",
                "embedding",
                "rerank",
                name="modelprofile",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("next_event_seq", sa.Integer(), nullable=False),
        sa.Column("context_generation", sa.Integer(), nullable=False),
        sa.Column("acl_epoch_at_start", sa.BigInteger(), nullable=False),
        sa.Column("auth_session_id", sa.Uuid(), nullable=True),
        sa.Column("step_up_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("steps_used", sa.Integer(), nullable=False),
        sa.Column("token_used", sa.BigInteger(), nullable=False),
        sa.Column("cost_micro_usd", sa.BigInteger(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("terminal_reason", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled')) = (finished_at IS NOT NULL)",
            name=op.f("ck_runs_finished_at_matches_terminal_status"),
        ),
        sa.CheckConstraint("mode IN ('public', 'owner')", name=op.f("ck_runs_mode_valid")),
        sa.CheckConstraint(
            "model_profile IN ('primary', 'fast', 'embedding', 'rerank')",
            name=op.f("ck_runs_model_profile_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'waiting_input', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "acl_epoch_at_start >= 0", name=op.f("ck_runs_acl_epoch_at_start_non_negative")
        ),
        sa.CheckConstraint(
            "context_generation >= 1", name=op.f("ck_runs_context_generation_positive")
        ),
        sa.CheckConstraint("cost_micro_usd >= 0", name=op.f("ck_runs_cost_micro_usd_non_negative")),
        sa.CheckConstraint("next_event_seq >= 1", name=op.f("ck_runs_next_event_seq_positive")),
        sa.CheckConstraint("steps_used >= 0", name=op.f("ck_runs_steps_used_non_negative")),
        sa.CheckConstraint("token_used >= 0", name=op.f("ck_runs_token_used_non_negative")),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_runs_auth_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_runs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quota_bucket_id"],
            ["quota_buckets.id"],
            name=op.f("fk_runs_quota_bucket_id_quota_buckets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_runs_user_id_idempotency_key"),
    )
    op.create_index(
        "ix_runs_conversation_id_created_at",
        "runs",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_runs_status_created_at", "runs", ["status", "created_at"], unique=False)
    op.create_index("ix_runs_user_id_status", "runs", ["user_id", "status"], unique=False)
    op.create_index(
        "uq_runs_conversation_id_non_terminal",
        "runs",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running', 'waiting_input')"),
    )
    op.create_table(
        "actions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "publish",
                "revoke",
                "delete",
                "update_settings",
                "provide_input",
                name="actionkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("target_version", sa.Integer(), nullable=True),
        sa.Column("args_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("args_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "executed",
                "rejected",
                "expired",
                name="actionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(confirmed_at IS NULL) = (status NOT IN ('confirmed', 'executed'))",
            name=op.f("ck_actions_confirmed_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(executed_at IS NULL) = (status <> 'executed')",
            name=op.f("ck_actions_executed_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(expired_at IS NULL) = (status <> 'expired')",
            name=op.f("ck_actions_expired_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(rejected_at IS NULL) = (status <> 'rejected')",
            name=op.f("ck_actions_rejected_at_matches_status"),
        ),
        sa.CheckConstraint(
            "kind IN ('publish', 'revoke', 'delete', 'update_settings', 'provide_input')",
            name=op.f("ck_actions_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'executed', 'rejected', 'expired')",
            name=op.f("ck_actions_status_valid"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_actions_expires_after_created")
        ),
        sa.CheckConstraint(
            "target_version IS NULL OR target_version >= 0",
            name=op.f("ck_actions_target_version_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_actions_actor_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_actions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint(
            "run_id",
            "kind",
            "target_id",
            "target_version",
            "args_hash",
            name="uq_actions_idempotency_identity",
        ),
    )
    op.create_index("ix_actions_run_id_status", "actions", ["run_id", "status"], unique=False)
    op.create_index(
        "ix_actions_status_expires_at", "actions", ["status", "expires_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(status = 'running') = (lease_token IS NOT NULL) AND (status = 'running') = (lease_expires_at IS NOT NULL)",
            name=op.f("ck_jobs_lease_fields_match_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled')) = (finished_at IS NOT NULL)",
            name=op.f("ck_jobs_finished_at_matches_terminal_status"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_jobs_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_jobs_priority_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_jobs_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_lease_expires_at", "jobs", ["lease_expires_at"], unique=False)
    op.create_index("ix_jobs_run_id", "jobs", ["run_id"], unique=False)
    op.create_index("ix_jobs_status_available_at", "jobs", ["status", "available_at"], unique=False)
    op.create_index(
        "uq_jobs_type_dedupe_active",
        "jobs",
        ["job_type", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued', 'running')"),
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "assistant",
                "system",
                "tool",
                name="messagerole",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("tool_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(role = 'tool') = (tool_name IS NOT NULL)",
            name=op.f("ck_messages_tool_name_matches_role"),
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system', 'tool')", name=op.f("ck_messages_role_valid")
        ),
        sa.CheckConstraint(
            "content_version >= 1", name=op.f("ck_messages_content_version_positive")
        ),
        sa.CheckConstraint("seq >= 1", name=op.f("ck_messages_seq_positive")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_messages_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_messages_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "seq", name="uq_messages_conversation_seq"),
    )
    op.create_index(
        "ix_messages_conversation_id_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    op.create_table(
        "quota_reservations",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "reserved",
                "charged",
                "released",
                "refunded",
                name="quotareservationstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("charged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settle_reason", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status <> 'reserved' OR charged_at IS NULL",
            name=op.f("ck_quota_reservations_reserved_not_charged"),
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'charged', 'released', 'refunded')",
            name=op.f("ck_quota_reservations_status_valid"),
        ),
        sa.CheckConstraint("amount = 1", name=op.f("ck_quota_reservations_amount_is_one")),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["quota_buckets.id"],
            name=op.f("fk_quota_reservations_bucket_id_quota_buckets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_quota_reservations_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quota_reservations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_reservations")),
        sa.UniqueConstraint("run_id", name="uq_quota_reservations_run_id"),
    )
    op.create_index(
        "ix_quota_reservations_bucket_id_status",
        "quota_reservations",
        ["bucket_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_quota_reservations_user_id_created_at",
        "quota_reservations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "run.started",
                "message.delta",
                "message.snapshot",
                "tool.call",
                "tool.result",
                "source.recorded",
                "action.required",
                "run.invalidated",
                "run.terminal",
                name="eventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("object_version", sa.Integer(), nullable=True),
        sa.Column("context_generation", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('run.started', 'message.delta', 'message.snapshot', 'tool.call', 'tool.result', 'source.recorded', 'action.required', 'run.invalidated', 'run.terminal')",
            name=op.f("ck_run_events_event_type_valid"),
        ),
        sa.CheckConstraint(
            "context_generation IS NULL OR context_generation >= 1",
            name=op.f("ck_run_events_context_generation_positive"),
        ),
        sa.CheckConstraint(
            "object_version IS NULL OR object_version >= 0",
            name=op.f("ck_run_events_object_version_non_negative"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_run_events_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", "seq", name="pk_run_events"),
    )
    op.create_index(
        "ix_run_events_run_id_created_at", "run_events", ["run_id", "created_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_session_id", sa.Uuid(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("before_version", sa.Integer(), nullable=True),
        sa.Column("after_version", sa.Integer(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "after_version IS NULL OR after_version >= 0",
            name=op.f("ck_audit_events_after_version_non_negative"),
        ),
        sa.CheckConstraint(
            "before_version IS NULL OR before_version >= 0",
            name=op.f("ck_audit_events_before_version_non_negative"),
        ),
        sa.CheckConstraint("length(action) > 0", name=op.f("ck_audit_events_action_not_empty")),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_audit_events_actor_session_id_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_audit_events_publication_id_publications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_audit_events_resource_id_resources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_audit_events_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_action_created_at", "audit_events", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_actor_id_created_at",
        "audit_events",
        ["actor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_resource_id_created_at",
        "audit_events",
        ["resource_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_audit_events_run_id", "audit_events", ["run_id"], unique=False)
    op.create_table(
        "provider_calls",
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "chat",
                "tool",
                "embedding",
                "rerank",
                "search",
                "fetch",
                "email",
                name="providercallpurpose",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "prepared",
                "dispatched",
                "succeeded",
                "failed",
                "unknown",
                name="providercallstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("provider_call_id", sa.String(length=128), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micro_usd", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('chat', 'tool', 'embedding', 'rerank', 'search', 'fetch', 'email')",
            name=op.f("ck_provider_calls_purpose_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'prepared' OR dispatched_at IS NULL",
            name=op.f("ck_provider_calls_prepared_not_dispatched"),
        ),
        sa.CheckConstraint(
            "status IN ('prepared', 'dispatched', 'succeeded', 'failed', 'unknown')",
            name=op.f("ck_provider_calls_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'unknown') = (settled_at IS NOT NULL)",
            name=op.f("ck_provider_calls_settled_at_matches_status"),
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_provider_calls_attempt_no_positive")),
        sa.CheckConstraint(
            "cost_micro_usd IS NULL OR cost_micro_usd >= 0",
            name=op.f("ck_provider_calls_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_provider_calls_input_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "job_id IS NOT NULL OR run_id IS NOT NULL",
            name=op.f("ck_provider_calls_traceable_target"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_provider_calls_latency_non_negative"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_provider_calls_output_tokens_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_provider_calls_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_provider_calls_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_calls")),
        sa.UniqueConstraint(
            "job_id", "purpose", "attempt_no", name="uq_provider_calls_job_purpose_attempt"
        ),
    )
    op.create_index(
        "ix_provider_calls_provider_call_id", "provider_calls", ["provider_call_id"], unique=False
    )
    op.create_index("ix_provider_calls_run_id", "provider_calls", ["run_id"], unique=False)
    op.create_index(
        "ix_provider_calls_status_created_at",
        "provider_calls",
        ["status", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_run_sources_run_id_runs"),
        "run_sources",
        "runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_run_sources_run_id_runs"), "run_sources", type_="foreignkey")
    op.drop_index("ix_provider_calls_status_created_at", table_name="provider_calls")
    op.drop_index("ix_provider_calls_run_id", table_name="provider_calls")
    op.drop_index("ix_provider_calls_provider_call_id", table_name="provider_calls")
    op.drop_table("provider_calls")
    op.drop_index("ix_audit_events_run_id", table_name="audit_events")
    op.drop_index("ix_audit_events_resource_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_action_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_run_events_run_id_created_at", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_quota_reservations_user_id_created_at", table_name="quota_reservations")
    op.drop_index("ix_quota_reservations_bucket_id_status", table_name="quota_reservations")
    op.drop_table("quota_reservations")
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "uq_jobs_type_dedupe_active",
        table_name="jobs",
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued', 'running')"),
    )
    op.drop_index("ix_jobs_status_available_at", table_name="jobs")
    op.drop_index("ix_jobs_run_id", table_name="jobs")
    op.drop_index("ix_jobs_lease_expires_at", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_actions_status_expires_at", table_name="actions")
    op.drop_index("ix_actions_run_id_status", table_name="actions")
    op.drop_table("actions")
    op.drop_index(
        "uq_runs_conversation_id_non_terminal",
        table_name="runs",
        postgresql_where=sa.text("status IN ('pending', 'running', 'waiting_input')"),
    )
    op.drop_index("ix_runs_user_id_status", table_name="runs")
    op.drop_index("ix_runs_status_created_at", table_name="runs")
    op.drop_index("ix_runs_conversation_id_created_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_quota_buckets_window_start", table_name="quota_buckets")
    op.drop_table("quota_buckets")
    op.drop_index("ix_conversations_user_id_last_activity_at", table_name="conversations")
    op.drop_index("ix_conversations_user_id_created_at", table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
