"""content files comments reports

Revision ID: f91f72539039
Revises: 8585dcac6197
Create Date: 2026-10-05 19:28:38.062978

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "f91f72539039"
down_revision: str | None = "8585dcac6197"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 本批需要挂 updated_at 触发器的表（只追加表不在其中）。
_TIMESTAMPED_TABLES: tuple[str, ...] = (
    "retention_policies",
    "resources",
    "file_objects",
    "resource_versions",
    "publications",
    "comments",
    "reports",
)


def upgrade() -> None:
    # 幂等：函数可能已由前批迁移创建。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retention_policies",
        sa.Column(
            "scope",
            sa.Enum(
                "resources",
                "conversations",
                "audit_events",
                "runtime_logs",
                name="retentionscope",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "resource_kind",
            sa.Enum(
                "article",
                "bookmark",
                "document",
                "webpage",
                name="resourcekind",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "mode",
            sa.Enum("forever", "ttl", name="retentionmode", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("ttl_days", sa.Integer(), nullable=True),
        sa.Column(
            "anchor",
            sa.Enum(
                "created_at", "updated_at", name="retentionanchor", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "applies_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("include_existing", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(mode = 'forever' AND ttl_days IS NULL) "
            "OR (mode = 'ttl' AND ttl_days IS NOT NULL AND ttl_days > 0)",
            name=op.f("ck_retention_policies_ttl_matches_mode"),
        ),
        sa.CheckConstraint(
            "anchor IN ('created_at', 'updated_at')",
            name=op.f("ck_retention_policies_anchor_valid"),
        ),
        sa.CheckConstraint(
            "mode IN ('forever', 'ttl')", name=op.f("ck_retention_policies_mode_valid")
        ),
        sa.CheckConstraint(
            "resource_kind IN ('article', 'bookmark', 'document', 'webpage')",
            name=op.f("ck_retention_policies_resource_kind_valid"),
        ),
        sa.CheckConstraint(
            "scope IN ('resources', 'conversations', 'audit_events', 'runtime_logs')",
            name=op.f("ck_retention_policies_scope_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_retention_policies_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_policies")),
    )
    op.create_index(
        "uq_retention_policies_active_global",
        "retention_policies",
        ["scope"],
        unique=True,
        postgresql_where=sa.text("is_active AND resource_kind IS NULL"),
    )
    op.create_index(
        "uq_retention_policies_active_kind",
        "retention_policies",
        ["scope", "resource_kind"],
        unique=True,
        postgresql_where=sa.text("is_active AND resource_kind IS NOT NULL"),
    )
    op.create_table(
        "resources",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "article",
                "bookmark",
                "document",
                "webpage",
                name="resourcekind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("acl_version", sa.BigInteger(), nullable=False),
        sa.Column("retention_policy_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('article', 'bookmark', 'document', 'webpage')",
            name=op.f("ck_resources_kind_valid"),
        ),
        sa.CheckConstraint("acl_version >= 0", name=op.f("ck_resources_acl_version_non_negative")),
        sa.CheckConstraint("length(slug) > 0", name=op.f("ck_resources_slug_not_empty")),
        sa.ForeignKeyConstraint(
            ["current_revision_id", "id"],
            ["resource_versions.id", "resource_versions.resource_id"],
            name="fk_resources_current_revision_id_resource_versions",
            # NO ACTION 而不是 SET NULL：SET NULL 会把列组里每一列都置空，
            # 而 id 是 NOT NULL 主键，该动作永远无法完成。
            #
            # 注意：use_alter=True 的内联声明**不会**被本迁移发射，
            # 实际的 op.create_foreign_key 在批次三（2c485916b4d2）。
            # 两边必须同时修改，否则只有内联声明被改、库里仍是旧动作。
            ondelete="NO ACTION",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_resources_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["retention_policy_id"],
            ["retention_policies.id"],
            name=op.f("fk_resources_retention_policy_id_retention_policies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("id", "owner_id", name="uq_resources_id_owner_id"),
        sa.UniqueConstraint("slug", name="uq_resources_slug"),
    )
    op.create_index(
        "ix_resources_active_owner_id",
        "resources",
        ["owner_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "ix_resources_expires_at",
        "resources",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_resources_owner_id_kind_created_at",
        "resources",
        ["owner_id", "kind", "created_at"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "hidden",
                name="commentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("moderated_by", sa.Uuid(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'hidden')",
            name=op.f("ck_comments_status_valid"),
        ),
        sa.CheckConstraint("length(body) > 0", name=op.f("ck_comments_body_not_empty")),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_comments_parent_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["moderated_by"],
            ["users.id"],
            name=op.f("fk_comments_moderated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id", "resource_id"],
            ["comments.id", "comments.resource_id"],
            name="fk_comments_parent_id_resource_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_comments_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint("author_id", "client_id", name="uq_comments_author_client"),
        sa.UniqueConstraint("id", "resource_id", name="uq_comments_id_resource_id"),
    )
    op.create_index(
        "ix_comments_author_id_created_at", "comments", ["author_id", "created_at"], unique=False
    )
    op.create_index("ix_comments_parent_id", "comments", ["parent_id"], unique=False)
    op.create_index(
        "ix_comments_resource_id_status_created_at",
        "comments",
        ["resource_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "file_objects",
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "staged",
                "ready",
                "pending_delete",
                "failed",
                name="fileobjectstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ready') = (finalized_at IS NOT NULL)",
            name=op.f("ck_file_objects_finalized_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('staged', 'ready', 'pending_delete', 'failed')",
            name=op.f("ck_file_objects_status_valid"),
        ),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_file_objects_byte_size_non_negative")),
        sa.CheckConstraint(
            "length(object_key) > 0", name=op.f("ck_file_objects_object_key_not_empty")
        ),
        sa.CheckConstraint("length(sha256) > 0", name=op.f("ck_file_objects_sha256_not_empty")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_file_objects_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_file_objects_resource_id_resources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_objects")),
        sa.UniqueConstraint("object_key", name="uq_file_objects_object_key"),
    )
    op.create_index("ix_file_objects_resource_id", "file_objects", ["resource_id"], unique=False)
    op.create_index(
        "ix_file_objects_status_created_at", "file_objects", ["status", "created_at"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "resolved", "dismissed", name="reportstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("handled_by", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status = 'open') = (resolved_at IS NULL)",
            name=op.f("ck_reports_resolved_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'dismissed')", name=op.f("ck_reports_status_valid")
        ),
        sa.CheckConstraint("length(reason) > 0", name=op.f("ck_reports_reason_not_empty")),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_reports_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["handled_by"],
            ["users.id"],
            name=op.f("fk_reports_handled_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index("ix_reports_comment_id", "reports", ["comment_id"], unique=False)
    op.create_index(
        "ix_reports_status_created_at", "reports", ["status", "created_at"], unique=False
    )
    op.create_index(
        "uq_reports_reporter_id_comment_id_open",
        "reports",
        ["reporter_id", "comment_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "resource_versions",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column(
            "content_format",
            sa.Enum("markdown", "plain", name="contentformat", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("private_note", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("linked_source_id", sa.Uuid(), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("file_object_key", sa.String(length=512), nullable=True),
        sa.Column("file_sha256", sa.Text(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "content_format IN ('markdown', 'plain')",
            name=op.f("ck_resource_versions_content_format_valid"),
        ),
        sa.CheckConstraint(
            "source_metadata IS NULL OR jsonb_typeof(source_metadata) = 'object'",
            name=op.f("ck_resource_versions_source_metadata_is_object"),
        ),
        sa.CheckConstraint(
            "(file_object_key IS NULL) = (file_sha256 IS NULL) AND (file_object_key IS NULL) = (media_type IS NULL) AND (file_object_key IS NULL) = (byte_size IS NULL)",
            name=op.f("ck_resource_versions_file_metadata_consistent"),
        ),
        sa.CheckConstraint(
            "byte_size IS NULL OR byte_size >= 0",
            name=op.f("ck_resource_versions_byte_size_non_negative"),
        ),
        sa.CheckConstraint(
            "revision_no >= 1", name=op.f("ck_resource_versions_revision_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_resource_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_object_key"],
            ["file_objects.object_key"],
            name=op.f("fk_resource_versions_file_object_key_file_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["linked_source_id"],
            ["resources.id"],
            name=op.f("fk_resource_versions_linked_source_id_resources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_resource_versions_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_versions")),
        sa.UniqueConstraint("resource_id", "id", name="uq_resource_versions_resource_id_id"),
        sa.UniqueConstraint(
            "resource_id", "revision_no", name="uq_resource_versions_resource_revision"
        ),
    )
    op.create_index(
        "ix_resource_versions_resource_id_created_at",
        "resource_versions",
        ["resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "publications",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("publication_no", sa.Integer(), nullable=False),
        sa.Column("public_title", sa.Text(), nullable=True),
        sa.Column("public_body", sa.Text(), nullable=True),
        sa.Column("public_note", sa.Text(), nullable=True),
        sa.Column("public_url", sa.Text(), nullable=True),
        sa.Column(
            "public_tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "public_fields",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("raw_download_enabled", sa.Boolean(), nullable=False),
        sa.Column("published_by", sa.Uuid(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "('body' = ANY(public_fields)) = (public_body IS NOT NULL)",
            name=op.f("ck_publications_public_body_matches_fields"),
        ),
        sa.CheckConstraint(
            "('note' = ANY(public_fields)) = (public_note IS NOT NULL)",
            name=op.f("ck_publications_public_note_matches_fields"),
        ),
        sa.CheckConstraint(
            "('tags' = ANY(public_fields)) = (cardinality(public_tags) > 0)",
            name=op.f("ck_publications_public_tags_matches_fields"),
        ),
        sa.CheckConstraint(
            "('title' = ANY(public_fields)) = (public_title IS NOT NULL)",
            name=op.f("ck_publications_public_title_matches_fields"),
        ),
        sa.CheckConstraint(
            "('url' = ANY(public_fields)) = (public_url IS NOT NULL)",
            name=op.f("ck_publications_public_url_matches_fields"),
        ),
        sa.CheckConstraint(
            "public_fields <@ ARRAY['title', 'body', 'note', 'url', 'tags']::text[]",
            name=op.f("ck_publications_public_fields_whitelisted"),
        ),
        sa.CheckConstraint(
            "publication_no >= 1", name=op.f("ck_publications_publication_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_publications_published_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id", "revision_id"],
            ["resource_versions.resource_id", "resource_versions.id"],
            name="fk_publications_resource_id_revision_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_publications_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint(
            "resource_id", "publication_no", name="uq_publications_resource_publication"
        ),
        sa.UniqueConstraint(
            "resource_id", "revision_id", "id", name="uq_publications_resource_revision_id"
        ),
    )
    op.create_index(
        "ix_publications_resource_id_published_at",
        "publications",
        ["resource_id", "published_at"],
        unique=False,
    )
    op.create_index(
        "uq_publications_resource_id_current",
        "publications",
        ["resource_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_publications_resource_id_current",
        table_name="publications",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_publications_resource_id_published_at", table_name="publications")
    op.drop_table("publications")
    op.drop_index("ix_resource_versions_resource_id_created_at", table_name="resource_versions")
    op.drop_table("resource_versions")
    op.drop_index(
        "uq_reports_reporter_id_comment_id_open",
        table_name="reports",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_reports_status_created_at", table_name="reports")
    op.drop_index("ix_reports_comment_id", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_file_objects_status_created_at", table_name="file_objects")
    op.drop_index("ix_file_objects_resource_id", table_name="file_objects")
    op.drop_table("file_objects")
    op.drop_index("ix_comments_resource_id_status_created_at", table_name="comments")
    op.drop_index("ix_comments_parent_id", table_name="comments")
    op.drop_index("ix_comments_author_id_created_at", table_name="comments")
    op.drop_table("comments")
    op.drop_index("ix_resources_owner_id_kind_created_at", table_name="resources")
    op.drop_index(
        "ix_resources_expires_at",
        table_name="resources",
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.drop_index(
        "ix_resources_active_owner_id",
        table_name="resources",
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_table("resources")
    op.drop_index(
        "uq_retention_policies_active_kind",
        table_name="retention_policies",
        postgresql_where=sa.text("is_active AND resource_kind IS NOT NULL"),
    )
    op.drop_index(
        "uq_retention_policies_active_global",
        table_name="retention_policies",
        postgresql_where=sa.text("is_active AND resource_kind IS NULL"),
    )
    op.drop_table("retention_policies")
    # ### end Alembic commands ###
