"""knowledge sources summaries memories

Revision ID: c8dc294b55a0
Revises: 2c485916b4d2
Create Date: 2026-10-05 19:32:29.162957

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "c8dc294b55a0"
down_revision: str | None = "2c485916b4d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 本批需要挂 updated_at 触发器的表（只追加表不在其中）。
#: knowledge_chunks 与 run_sources 只有 created_at，因此不挂触发器。
_TIMESTAMPED_TABLES: tuple[str, ...] = (
    "knowledge_indexes",
    "conversation_summaries",
    "memories",
)


def upgrade() -> None:
    # 幂等：函数可能已由前批迁移创建。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_summaries",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("upto_message_seq", sa.BigInteger(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("scope_epoch", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "stale", name="summarystatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'stale')", name=op.f("ck_conversation_summaries_status_valid")
        ),
        sa.CheckConstraint(
            "length(body_text) > 0", name=op.f("ck_conversation_summaries_body_text_not_empty")
        ),
        sa.CheckConstraint(
            "scope_epoch >= 0", name=op.f("ck_conversation_summaries_scope_epoch_non_negative")
        ),
        sa.CheckConstraint(
            "upto_message_seq >= 1",
            name=op.f("ck_conversation_summaries_upto_message_seq_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_summaries_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_summaries")),
    )
    op.create_index(
        "ix_conversation_summaries_conversation_id",
        "conversation_summaries",
        ["conversation_id", "upto_message_seq"],
        unique=False,
    )
    op.create_index(
        "uq_conversation_summaries_active",
        "conversation_summaries",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "memories",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("preference", "fact", name="memorykind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("origin_run_id", sa.Uuid(), nullable=True),
        sa.Column("origin_message_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('preference', 'fact')", name=op.f("ck_memories_kind_valid")),
        sa.CheckConstraint(
            "length(content_text) > 0", name=op.f("ck_memories_content_text_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["origin_message_id"],
            ["messages.id"],
            name=op.f("fk_memories_origin_message_id_messages"),
            ondelete="SET NULL",
        ),
        # 来源 run 用**单列**外键：原先是 (origin_run_id, user_id) 复合外键并声明
        # SET NULL，但 SET NULL 会把列组里每一列都置空，而 user_id 是 NOT NULL，
        # 该动作永远无法完成。"来源 run 属于同一用户"改由 service 校验。
        sa.ForeignKeyConstraint(
            ["origin_run_id"],
            ["runs.id"],
            name=op.f("fk_memories_origin_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_active_user_id",
        "memories",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_memories_user_id_created_at", "memories", ["user_id", "created_at"], unique=False
    )
    op.create_index("ix_memories_origin_run_id", "memories", ["origin_run_id"], unique=False)
    op.create_table(
        "knowledge_indexes",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("owner", "public", name="indexscope", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("embedding_provider", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "building",
                "ready",
                "failed",
                "retired",
                name="indexstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'public') = (publication_id IS NOT NULL)",
            name=op.f("ck_knowledge_indexes_publication_id_matches_scope"),
        ),
        sa.CheckConstraint(
            "NOT is_active OR status = 'ready'",
            name=op.f("ck_knowledge_indexes_active_must_be_ready"),
        ),
        sa.CheckConstraint(
            "scope IN ('owner', 'public')", name=op.f("ck_knowledge_indexes_scope_valid")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'building', 'ready', 'failed', 'retired')",
            name=op.f("ck_knowledge_indexes_status_valid"),
        ),
        sa.CheckConstraint(
            "embedding_dimension = 1024",
            name=op.f("ck_knowledge_indexes_embedding_dimension_matches_column"),
        ),
        sa.CheckConstraint(
            "generation >= 1", name=op.f("ck_knowledge_indexes_generation_positive")
        ),
        sa.CheckConstraint(
            "length(content_hash) > 0", name=op.f("ck_knowledge_indexes_content_hash_not_empty")
        ),
        sa.CheckConstraint(
            "length(embedding_model) > 0",
            name=op.f("ck_knowledge_indexes_embedding_model_not_empty"),
        ),
        sa.CheckConstraint(
            "length(embedding_provider) > 0",
            name=op.f("ck_knowledge_indexes_embedding_provider_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id", "revision_id", "publication_id"],
            ["publications.resource_id", "publications.revision_id", "publications.id"],
            name="fk_knowledge_indexes_resource_revision_publication",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id", "revision_id"],
            ["resource_versions.resource_id", "resource_versions.id"],
            name="fk_knowledge_indexes_resource_id_revision_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_knowledge_indexes_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_indexes")),
        sa.UniqueConstraint(
            "id", "embedding_dimension", name="uq_knowledge_indexes_id_embedding_dimension"
        ),
    )
    op.create_index(
        "ix_knowledge_indexes_resource_id_scope",
        "knowledge_indexes",
        ["resource_id", "scope"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_indexes_revision_id", "knowledge_indexes", ["revision_id"], unique=False
    )
    op.create_index(
        "uq_knowledge_indexes_owner_active",
        "knowledge_indexes",
        ["revision_id"],
        unique=True,
        postgresql_where=sa.text("is_active AND scope = 'owner'"),
    )
    op.create_index(
        "uq_knowledge_indexes_public_active",
        "knowledge_indexes",
        ["publication_id"],
        unique=True,
        postgresql_where=sa.text("is_active AND scope = 'public'"),
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("index_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_no", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "locator IS NULL OR jsonb_typeof(locator) = 'object'",
            name=op.f("ck_knowledge_chunks_locator_is_object"),
        ),
        sa.CheckConstraint("chunk_no >= 0", name=op.f("ck_knowledge_chunks_chunk_no_non_negative")),
        sa.CheckConstraint(
            "length(content_text) > 0", name=op.f("ck_knowledge_chunks_content_text_not_empty")
        ),
        sa.CheckConstraint(
            "token_count IS NULL OR token_count >= 0",
            name=op.f("ck_knowledge_chunks_token_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["knowledge_indexes.id"],
            name=op.f("fk_knowledge_chunks_index_id_knowledge_indexes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint("index_id", "chunk_no", name="uq_knowledge_chunks_index_chunk_no"),
    )
    # 唯一约束已为 (index_id, chunk_no) 建了索引，按 index_id 的前缀查询直接可用，
    # 因此不再重复建同列的普通 B-tree 索引。
    op.create_table(
        "run_sources",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("resource", "web", name="runsourcetype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("source_key", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column("index_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("observed_acl_version", sa.BigInteger(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("web_url", sa.Text(), nullable=True),
        sa.Column("web_title", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_type = 'resource' AND resource_id IS NOT NULL AND revision_id IS NOT NULL AND web_url IS NULL AND web_title IS NULL) OR (source_type = 'web' AND resource_id IS NULL AND revision_id IS NULL AND publication_id IS NULL AND index_id IS NULL AND chunk_id IS NULL AND web_url IS NOT NULL)",
            name=op.f("ck_run_sources_source_type_consistent"),
        ),
        sa.CheckConstraint(
            "locator IS NULL OR jsonb_typeof(locator) = 'object'",
            name=op.f("ck_run_sources_locator_is_object"),
        ),
        sa.CheckConstraint(
            "source_type IN ('resource', 'web')", name=op.f("ck_run_sources_source_type_valid")
        ),
        sa.CheckConstraint(
            "(index_id IS NULL) = (chunk_id IS NULL)",
            name=op.f("ck_run_sources_index_chunk_paired"),
        ),
        sa.CheckConstraint(
            "length(source_key) > 0", name=op.f("ck_run_sources_source_key_not_empty")
        ),
        sa.CheckConstraint(
            "observed_acl_version >= 0",
            name=op.f("ck_run_sources_observed_acl_version_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["knowledge_chunks.id"],
            name=op.f("fk_run_sources_chunk_id_knowledge_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["knowledge_indexes.id"],
            name=op.f("fk_run_sources_index_id_knowledge_indexes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_run_sources_publication_id_publications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id", "revision_id"],
            ["resource_versions.resource_id", "resource_versions.id"],
            name="fk_run_sources_resource_id_revision_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_sources_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_sources")),
        sa.UniqueConstraint("run_id", "source_key", name="uq_run_sources_run_id_source_key"),
    )
    op.create_index("ix_run_sources_resource_id", "run_sources", ["resource_id"], unique=False)
    op.create_index("ix_run_sources_run_id", "run_sources", ["run_id"], unique=False)
    op.create_foreign_key(
        "fk_runs_current_message_id_messages",
        "runs",
        "messages",
        ["current_message_id", "conversation_id"],
        ["id", "conversation_id"],
        ondelete="SET NULL",
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_runs_input_message_id_messages",
        "runs",
        "messages",
        ["input_message_id", "conversation_id"],
        ["id", "conversation_id"],
        ondelete="SET NULL",
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)


def downgrade() -> None:
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_runs_input_message_id_messages", "runs", type_="foreignkey")
    op.drop_constraint("fk_runs_current_message_id_messages", "runs", type_="foreignkey")
    op.drop_index("ix_run_sources_run_id", table_name="run_sources")
    op.drop_index("ix_run_sources_resource_id", table_name="run_sources")
    op.drop_table("run_sources")
    op.drop_table("knowledge_chunks")
    op.drop_index(
        "uq_knowledge_indexes_public_active",
        table_name="knowledge_indexes",
        postgresql_where=sa.text("is_active AND scope = 'public'"),
    )
    op.drop_index(
        "uq_knowledge_indexes_owner_active",
        table_name="knowledge_indexes",
        postgresql_where=sa.text("is_active AND scope = 'owner'"),
    )
    op.drop_index("ix_knowledge_indexes_revision_id", table_name="knowledge_indexes")
    op.drop_index("ix_knowledge_indexes_resource_id_scope", table_name="knowledge_indexes")
    op.drop_table("knowledge_indexes")
    op.drop_index("ix_memories_user_id_created_at", table_name="memories")
    op.drop_index("ix_memories_origin_run_id", table_name="memories")
    op.drop_index(
        "ix_memories_active_user_id",
        table_name="memories",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("memories")
    op.drop_index(
        "uq_conversation_summaries_active",
        table_name="conversation_summaries",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_conversation_summaries_conversation_id", table_name="conversation_summaries")
    op.drop_table("conversation_summaries")
    # ### end Alembic commands ###
