"""identity foundation

Revision ID: 8585dcac6197
Revises:
Create Date: 2026-10-05 19:28:26.602999

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autumn_backend.db.timestamps import (
    CREATE_UPDATED_AT_FUNCTION_SQL,
    DROP_UPDATED_AT_FUNCTION_SQL,
    drop_updated_at_trigger_statements,
    updated_at_trigger_statements,
)

# revision identifiers, used by Alembic.
revision: str = "8585dcac6197"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 本批需要挂 updated_at 触发器的表（只追加表不在其中）。
_TIMESTAMPED_TABLES: tuple[str, ...] = (
    "users",
    "auth_sessions",
    "auth_tokens",
    "admin_factors",
    "rate_limit_buckets",
    "settings",
)


def upgrade() -> None:
    # 幂等：函数可能已由前批迁移创建。
    op.execute(CREATE_UPDATED_AT_FUNCTION_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_buckets",
        sa.Column("scope_hash", sa.Text(), nullable=False),
        sa.Column("policy_key", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hits", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("hits >= 0", name=op.f("ck_rate_limit_buckets_hits_non_negative")),
        sa.CheckConstraint(
            "length(policy_key) > 0", name=op.f("ck_rate_limit_buckets_policy_key_not_empty")
        ),
        sa.CheckConstraint(
            "length(scope_hash) > 0", name=op.f("ck_rate_limit_buckets_scope_hash_not_empty")
        ),
        sa.CheckConstraint(
            "window_end > window_start", name=op.f("ck_rate_limit_buckets_window_ordered")
        ),
        sa.PrimaryKeyConstraint(
            "scope_hash", "policy_key", "window_start", name="pk_rate_limit_buckets"
        ),
    )
    op.create_index(
        "ix_rate_limit_buckets_expires_at", "rate_limit_buckets", ["expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email_normalized", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "owner", name="userrole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_verification",
                "active",
                "disabled",
                name="userstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auth_version", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('member', 'owner')", name=op.f("ck_users_role_valid")),
        sa.CheckConstraint(
            "status IN ('pending_verification', 'active', 'disabled')",
            name=op.f("ck_users_status_valid"),
        ),
        sa.CheckConstraint("auth_version >= 1", name=op.f("ck_users_auth_version_positive")),
        sa.CheckConstraint(
            "email_normalized = lower(btrim(email_normalized))",
            name=op.f("ck_users_email_normalized_canonical"),
        ),
        sa.CheckConstraint(
            "length(email_normalized) > 0", name=op.f("ck_users_email_normalized_not_empty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_normalized", name="uq_users_email_normalized"),
    )
    op.create_index("ix_users_status_created_at", "users", ["status", "created_at"], unique=False)
    op.create_table(
        "admin_factors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("totp", name="adminfactorkind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("secret_ciphertext", sa.Text(), nullable=False),
        sa.Column("encryption_key_version", sa.BigInteger(), nullable=False),
        sa.Column("last_used_time_step", sa.BigInteger(), nullable=True),
        sa.Column("recovery_code_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("kind IN ('totp')", name=op.f("ck_admin_factors_kind_valid")),
        sa.CheckConstraint(
            "encryption_key_version >= 1",
            name=op.f("ck_admin_factors_encryption_key_version_positive"),
        ),
        sa.CheckConstraint(
            "length(secret_ciphertext) > 0",
            name=op.f("ck_admin_factors_secret_ciphertext_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_factors_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_factors")),
        sa.UniqueConstraint("user_id", name="uq_admin_factors_user_id"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("csrf_version", sa.BigInteger(), nullable=False),
        sa.Column("auth_version", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step_up_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "absolute_expires_at > created_at",
            name=op.f("ck_auth_sessions_absolute_expires_after_created"),
        ),
        sa.CheckConstraint(
            "auth_version >= 1", name=op.f("ck_auth_sessions_auth_version_positive")
        ),
        sa.CheckConstraint(
            "csrf_version >= 1", name=op.f("ck_auth_sessions_csrf_version_positive")
        ),
        sa.CheckConstraint(
            "idle_expires_at <= absolute_expires_at",
            name=op.f("ck_auth_sessions_idle_within_absolute_expiry"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("id", "user_id", name="uq_auth_sessions_id_user_id"),
        sa.UniqueConstraint("token_hash", name="uq_auth_sessions_token_hash"),
    )
    op.create_index(
        "ix_auth_sessions_absolute_expires_at",
        "auth_sessions",
        ["absolute_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_auth_sessions_idle_expires_at_active",
        "auth_sessions",
        ["idle_expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "auth_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "verify_email",
                "reset_password",
                name="authtokenpurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('verify_email', 'reset_password')",
            name=op.f("ck_auth_tokens_purpose_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_auth_tokens_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_tokens_expires_after_created")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_auth_tokens_token_hash"),
    )
    op.create_index("ix_auth_tokens_expires_at", "auth_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_auth_tokens_user_id_purpose", "auth_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key = lower(key)", name=op.f("ck_settings_key_lowercase")),
        sa.CheckConstraint("length(key) > 0", name=op.f("ck_settings_key_not_empty")),
        sa.CheckConstraint("schema_version >= 1", name=op.f("ck_settings_schema_version_positive")),
        sa.CheckConstraint("version >= 0", name=op.f("ck_settings_version_non_negative")),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###

    # 为每张带 updated_at 的表挂触发器（autogenerate 不涉及触发器）。
    # 每条 DDL 必须独立执行：asyncpg 不接受一次预编译多条命令。
    for table_name in _TIMESTAMPED_TABLES:
        for statement in updated_at_trigger_statements(table_name):
            op.execute(statement)

    # 全站公开权限 epoch 的初始化责任固定在迁移上：缺行**不得**被当成有效的 0，
    # Repository 读取时必须区分"没有这一行"与"值是 0"。
    op.execute(
        """
        INSERT INTO settings (key, value, schema_version, version, created_at, updated_at)
        VALUES ('content_acl_epoch', '0'::jsonb, 1, 0, now(), now())
        ON CONFLICT (key) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM settings WHERE key = 'content_acl_epoch'")
    for table_name in _TIMESTAMPED_TABLES:
        for statement in drop_updated_at_trigger_statements(table_name):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_index("ix_auth_tokens_user_id_purpose", table_name="auth_tokens")
    op.drop_index("ix_auth_tokens_expires_at", table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_index(
        "ix_auth_sessions_idle_expires_at_active",
        table_name="auth_sessions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_auth_sessions_absolute_expires_at", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("admin_factors")
    op.drop_index("ix_users_status_created_at", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_rate_limit_buckets_expires_at", table_name="rate_limit_buckets")
    op.drop_table("rate_limit_buckets")
    # ### end Alembic commands ###

    # 所有表都删完之后才可移除触发器函数。
    op.execute(DROP_UPDATED_AT_FUNCTION_SQL)
